# Generated by Django 5.0.1 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('ID_Vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('Marque', models.CharField(max_length=255)),
                ('Modele', models.CharField(max_length=255)),
                ('Immatriculation', models.CharField(max_length=255)),
                ('Kilometrage', models.IntegerField()),
                ('Date_Acquisition', models.DateField()),
                ('Date_Mise_En_Service', models.DateField()),
                ('Statut', models.CharField(max_length=255)),
            ],
        ),
    ]
