# Generated by Django 5.0.1 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reparation',
            fields=[
                ('ID_Reparation', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Vehicule', models.CharField(max_length=100, unique=True)),
                ('Description_Panne', models.TextField()),
                ('Date_Panne', models.DateField()),
                ('Date_Reparation', models.DateField()),
                ('Cout_Reparation', models.IntegerField()),
            ],
        ),
    ]
