# Generated by Django 5.0.1 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emplacement_parking',
            fields=[
                ('ID_Emplacement', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Emplacement', models.CharField(max_length=255)),
                ('Disponibilite', models.CharField(choices=[('occupé', 'Occupé'), ('libre', 'Libre')], max_length=10)),
            ],
        ),
    ]
