# Generated by Django 5.0.1 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conducteur',
            fields=[
                ('ID_Conducteur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('Numero_Telephone', models.CharField(max_length=255)),
            ],
        ),
    ]
